### ISSUE TITLE
read_nested_dict_from_hdf5 returns wrong dictionary keys

### ISSUE THREAD

**Issue by pmrv** [h5io/h5io_browser#60]
When writing a non-json'able dict to HDF5, h5io prepends 'key_' to the group names and strips them on reading.  For `h5io_browser`, 'read_dict_from_hdf5` does this as well, but `read_nested_dict_from_hdf5` does not.  See MWE below.

```python
data = {'b': 42, 'array': np.ones(4) * 42}

import h5io

h5io.write_hdf5('test.h5', data)

h5io.read_hdf5('test.h5', 'h5io')

import h5io_browser

h5io_browser.read_dict_from_hdf('test.h5', 'h5io')

h5io_browser.read_nested_dict_from_hdf('test.h5', 'h5io')
```

**Comment by jan-janssen** [comment]
@pmrv I fixed the issue in https://github.com/h5io/h5io_browser/pull/61 and added the example as test. Can you check if that solves your issue? Then I can merge the pull request and release a new version.
